/* Generated by Yosys 0.19+36 (git sha1 15393442d61, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_brg(clk, reset, sel, clkout);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  input clk;
  wire clk;
  output clkout;
  wire clkout;
  wire [5:0] cnt1;
  wire [1:0] cnt2;
  wire [2:0] cnt3;
  wire [3:0] cnt4;
  input reset;
  wire reset;
  input [1:0] sel;
  wire [1:0] sel;
  sky130_fd_sc_hd__nor2_1 _107_ (
    .A(sel[0]),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(sel[0]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(sel[1]),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _111_ (
    .A(_063_),
    .B(_058_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a21oi_1 _112_ (
    .A1(_055_),
    .A2(sel[1]),
    .B1(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand3_1 _113_ (
    .A(_051_),
    .B(_053_),
    .C(_054_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand3_1 _114_ (
    .A(_066_),
    .B(_056_),
    .C(sel[1]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _115_ (
    .A(_058_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor3_1 _116_ (
    .A(_060_),
    .B(_062_),
    .C(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _117_ (
    .A(sel[1]),
    .B(sel[0]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _118_ (
    .A(reset),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _119_ (
    .A(cnt4[2]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand4_1 _120_ (
    .A(_072_),
    .B(cnt4[0]),
    .C(cnt4[1]),
    .D(cnt4[3]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(_073_),
    .B(_071_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _122_ (
    .A(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand4_1 _123_ (
    .A(_069_),
    .B(_067_),
    .C(_049_),
    .D(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _124_ (
    .A1(_049_),
    .A2(_065_),
    .B1(_076_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _125_ (
    .A(cnt4[1]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xor2_1 _126_ (
    .A(cnt4[0]),
    .B(cnt4[1]),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand4_1 _127_ (
    .A(_069_),
    .B(_067_),
    .C(_075_),
    .D(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o21ai_0 _128_ (
    .A1(_077_),
    .A2(_065_),
    .B1(_079_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _129_ (
    .A(cnt4[0]),
    .B(cnt4[1]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _130_ (
    .A(cnt4[2]),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand4_1 _131_ (
    .A(_069_),
    .B(_067_),
    .C(_075_),
    .D(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _132_ (
    .A1(_072_),
    .A2(_065_),
    .B1(_082_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _133_ (
    .A(cnt4[3]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand3_1 _134_ (
    .A(cnt4[0]),
    .B(cnt4[1]),
    .C(cnt4[2]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _135_ (
    .A(cnt4[3]),
    .B(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand4_1 _136_ (
    .A(_069_),
    .B(_067_),
    .C(_075_),
    .D(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _137_ (
    .A1(_083_),
    .A2(_065_),
    .B1(_086_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(clkout),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(cnt1[4]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand3_1 _140_ (
    .A(_054_),
    .B(_088_),
    .C(cnt1[5]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor3_1 _141_ (
    .A(_050_),
    .B(cnt1[1]),
    .C(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _142_ (
    .A(cnt2[0]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(_091_),
    .B(cnt2[1]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor3b_1 _144_ (
    .A(reset),
    .B(sel[1]),
    .C_N(sel[0]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(_093_),
    .B(_092_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand3b_1 _146_ (
    .A_N(cnt3[1]),
    .B(cnt3[0]),
    .C(cnt3[2]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand4_1 _147_ (
    .A(_095_),
    .B(_056_),
    .C(sel[1]),
    .D(_061_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand3_1 _148_ (
    .A(_074_),
    .B(_094_),
    .C(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _149_ (
    .A1(_097_),
    .A2(_090_),
    .B1(_055_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _150_ (
    .A(_066_),
    .B(_056_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(_097_),
    .B(_090_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _152_ (
    .A(reset),
    .B(clkout),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand3_1 _153_ (
    .A(_100_),
    .B(_099_),
    .C(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o21ai_0 _154_ (
    .A1(_087_),
    .A2(_098_),
    .B1(_102_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _155_ (
    .A(_056_),
    .B(_057_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _156_ (
    .A(_103_),
    .B(cnt1[0]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o21ai_0 _157_ (
    .A1(reset),
    .A2(cnt1[0]),
    .B1(_104_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(cnt1[0]),
    .B(cnt1[1]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _159_ (
    .A(cnt1[0]),
    .B(cnt1[1]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a22oi_1 _160_ (
    .A1(cnt1[1]),
    .A2(_103_),
    .B1(_055_),
    .B2(_106_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(_105_),
    .B(_016_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _162_ (
    .A(cnt1[2]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor2_1 _163_ (
    .A(_017_),
    .B(_106_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a22oi_1 _165_ (
    .A1(cnt1[2]),
    .A2(_103_),
    .B1(_019_),
    .B2(_056_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_1 _166_ (
    .A1(_017_),
    .A2(_106_),
    .B1(_020_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(cnt1[3]),
    .B(_018_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(_018_),
    .B(cnt1[3]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a22oi_1 _169_ (
    .A1(cnt1[3]),
    .A2(_103_),
    .B1(_022_),
    .B2(_056_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_021_),
    .B(_023_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _171_ (
    .A(_103_),
    .B(cnt1[4]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o21ai_0 _172_ (
    .A1(_088_),
    .A2(_022_),
    .B1(_056_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a22oi_1 _173_ (
    .A1(_088_),
    .A2(_022_),
    .B1(_025_),
    .B2(_024_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor3_1 _174_ (
    .A(_088_),
    .B(_052_),
    .C(_022_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(_103_),
    .B(cnt1[5]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a31oi_1 _176_ (
    .A1(_018_),
    .A2(cnt1[3]),
    .A3(cnt1[4]),
    .B1(cnt1[5]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o31ai_1 _177_ (
    .A1(_099_),
    .A2(_028_),
    .A3(_026_),
    .B1(_027_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a22oi_1 _178_ (
    .A1(reset),
    .A2(_059_),
    .B1(_090_),
    .B2(_062_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand3_1 _179_ (
    .A(_093_),
    .B(_092_),
    .C(_091_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(_090_),
    .B(_062_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o211ai_1 _181_ (
    .A1(_056_),
    .A2(sel[1]),
    .B1(cnt2[0]),
    .C1(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__o21ai_0 _182_ (
    .A1(_030_),
    .A2(_029_),
    .B1(_032_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _183_ (
    .A(cnt2[1]),
    .B(_094_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(_033_),
    .B(cnt2[0]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o211ai_1 _185_ (
    .A1(_056_),
    .A2(sel[1]),
    .B1(cnt2[1]),
    .C1(_031_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o21ai_0 _186_ (
    .A1(_034_),
    .A2(_029_),
    .B1(_035_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _187_ (
    .A(cnt3[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_058_),
    .B(_061_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a21oi_1 _189_ (
    .A1(_055_),
    .A2(sel[1]),
    .B1(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _190_ (
    .A(_096_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _191_ (
    .A(_037_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand4_1 _192_ (
    .A(_067_),
    .B(_040_),
    .C(_036_),
    .D(_039_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _193_ (
    .A1(_036_),
    .A2(_038_),
    .B1(_041_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _194_ (
    .A(cnt3[1]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xor2_1 _195_ (
    .A(cnt3[0]),
    .B(cnt3[1]),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand4_1 _196_ (
    .A(_067_),
    .B(_040_),
    .C(_039_),
    .D(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _197_ (
    .A1(_042_),
    .A2(_038_),
    .B1(_044_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _198_ (
    .A(cnt3[2]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(cnt3[0]),
    .B(cnt3[1]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__xnor2_1 _200_ (
    .A(cnt3[2]),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand4_1 _201_ (
    .A(_067_),
    .B(_040_),
    .C(_039_),
    .D(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o21ai_0 _202_ (
    .A1(_045_),
    .A2(_038_),
    .B1(_048_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _203_ (
    .A(cnt4[0]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _204_ (
    .A(cnt1[0]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(cnt1[1]),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _206_ (
    .A(cnt1[5]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _207_ (
    .A(cnt1[4]),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _208_ (
    .A(cnt1[3]),
    .B(cnt1[2]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a31oi_1 _209_ (
    .A1(_051_),
    .A2(_053_),
    .A3(_054_),
    .B1(reset),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _210_ (
    .A(reset),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _211_ (
    .A(sel[1]),
    .B(sel[0]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_057_),
    .B(_056_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _213_ (
    .A(sel[1]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__dfxtp_1 _214_ (
    .CLK(clk),
    .D(_000_),
    .Q(cnt4[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _215_ (
    .CLK(clk),
    .D(_001_),
    .Q(cnt4[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _216_ (
    .CLK(clk),
    .D(_002_),
    .Q(cnt4[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _217_ (
    .CLK(clk),
    .D(_003_),
    .Q(cnt4[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _218_ (
    .CLK(clk),
    .D(_004_),
    .Q(clkout)
  );
  sky130_fd_sc_hd__dfxtp_1 _219_ (
    .CLK(clk),
    .D(_005_),
    .Q(cnt1[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _220_ (
    .CLK(clk),
    .D(_006_),
    .Q(cnt1[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _221_ (
    .CLK(clk),
    .D(_007_),
    .Q(cnt1[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _222_ (
    .CLK(clk),
    .D(_008_),
    .Q(cnt1[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _223_ (
    .CLK(clk),
    .D(_009_),
    .Q(cnt1[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _224_ (
    .CLK(clk),
    .D(_010_),
    .Q(cnt1[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _225_ (
    .CLK(clk),
    .D(_011_),
    .Q(cnt2[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _226_ (
    .CLK(clk),
    .D(_012_),
    .Q(cnt2[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _227_ (
    .CLK(clk),
    .D(_013_),
    .Q(cnt3[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _228_ (
    .CLK(clk),
    .D(_014_),
    .Q(cnt3[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _229_ (
    .CLK(clk),
    .D(_015_),
    .Q(cnt3[2])
  );
endmodule
